### ISSUE TITLE
Wedstrijdblad invullen en mailen of opsturen

### ISSUE THREAD

**Issue by JornHeyvaert** [TTC-AAlst/TTC-React-Front#34]
- [ ] Wedstrijdblad maken (scherm) voor VTTL 
- [ ] Wedstrijdblad maken (scherm) voor Sporta
- [ ] Wedstrijblad kunnen invullen en opslaan voor VTTL 
- [ ] Wedstrijblad kunnen invullen en opslaan voor Sporta
- [ ] Wedstrijblad doorsturen voor VTTL 
- [ ] Wedstrijblad doorsturen voor Sporta
- [ ] Wedstrijdblad afdrukken voor VTTL 
- [ ] Wedstrijdblad afdrukken voor Sporta

**Comment by Laoujin** [comment]
Beginnen met Sporta, daar was vraag naar door Jelle
Voor Vttl hebben we dat officieel programma
